# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - poc/azure

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '17.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'npm install'

  - script: |
      npm run test:contract
    displayName: 'contract test'

  - script: |
      yarn cleanstart &
    displayName: 'start server'

  - script: |
      npx cypress verify
    displayName: 'verify cypress'

  - script: |
      npm run test:functional
    displayName: 'Functional tests'