name: Integration Tests
on:
  push:
    branches:
      - integration-tests
  pull_request:
    branches:
      - dev
jobs:
  integration_tests:
    runs-on: macos-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: npm install

      - name: Contract tests
        run: npm run test:contract

      - name: Start site server
        run: npm run cleanstart &

      - name: Verify Cypress
        run: npx cypress verify

      - name: Functional tests
        run: npm run test:functional

      - name: Percy Visual Regression
        run: npx percy exec -- cypress run --spec 'cypress/integration/visualRegression/visualRegression.spec.js' -q
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload files to S3 with AWS CLI
        run: |
          aws s3 sync public/ s3://${{ secrets.S3_BUCKET_NAME }} --delete
